### ISSUE TITLE
Starting on MP world in edit mode

### ISSUE THREAD

**Issue by TruckerTorpedo** [FTBTeam/FTB-Pyramid-Reborn-3.0#11]
* **Modpack Version**: 3.0.0

* **Issue**: Starting a MP world, i can edit quests and finnish them instantly without required item made.

* **Is it Repeatable?**: Yes all quests can be edited and completed instantly.

* **Mod/s Affected**: Ftb Quests

* **Known Fix**: Disable edit-mode on the template, i think?

**Comment by DinnerBeef** [comment]
know idea how that can be since edit mode is per players will look into this

**Comment by 016Nojr** [comment]
Shouldnt do that anymore, can you verify?

**Comment by TruckerTorpedo** [comment]
Yes, cant complete quests by just clicking on them anymore. Seems fixed.
