### ISSUE TITLE
Crash when traveling through Deep Dark Portal

### ISSUE THREAD

**Issue by portega** [FTBTeam/FTB-Pyramid-Reborn-3.0#13]
* **Modpack Version**: 3.0.0

* **Issue**: The game crashes when the Deep Dark portal animation ends. 
* **Link to Log or Crash File Paste**: 
[crash-2018-10-10_21.05.27-server.txt](https://github.com/FTBTeam/FTB-Pyramid-Reborn-3.0/files/2466187/crash-2018-10-10_21.05.27-server.txt)

* **Is it Repeatable?**: Yes, also another user reported this in the forums

* **Mod/s Affected**: Extra Utilities 2

* **Known Fix**: N/A

**Comment by DinnerBeef** [comment]
Not fixing your are not supposed to be crafting or useing this item anyway we’ll be disbleing the the next update

**Comment by portega** [comment]
OK, thanks, didn't know it.

**Comment by willurd** [comment]
The Deep Dark portal is still enabled and still crashes the game.
