### ISSUE TITLE
No passive animals spawn.

### ISSUE THREAD

**Issue by TruckerTorpedo** [FTBTeam/FTB-Pyramid-Reborn-3.0#4]
* **Modpack Version**: 3.0.0 Single Player

* **Issue**: i have a 8x8 area of grass, and afk-ing 25-30 blocks from the platform overnight spawned no animals/passive mobs of any kind. could this be a issue with spawn chunk? i will try moving the grass platform much further away from the start-platform, to see if it fixes it.

* **Link to Log or Crash File Paste**: 
* **Is it Repeatable?**: Have not tried a second playthrough yet.

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by DinnerBeef** [comment]
Passive Mobs are have been tricky to get spawned forever in skyblocks. For this is reason we did add recipes for the spawn eggs. There are a few that are missing form the recipes which well be added in the next update.

**Comment by TruckerTorpedo** [comment]
i think i found the issue. spawning mobs on skyblocks is not a issue on singleplayer tho, unless there is spawn protection on. im guessing it is on here, cause my area was within the 4 chunks surrounding spawn. moved it 4-5 chunks straight out from the island with the monument behind me, and now i have sheeps and chickens. i knew there was spawn eggs, just didnt notice there was for the regular passive mobs like chicken sheep cow and pig :p now i know. TLDR; i think there is something preventing passive mobs from spawning around the spawn chunks.

**Comment by DinnerBeef** [comment]
There is nothing that is preventing mobs form spawning as I had mobs spawn right next to the quest island when i did my play thew.

**Comment by TruckerTorpedo** [comment]
probably veeery bad rng then. will test further when i start a new playthrough.
