### ISSUE TITLE
Resource Gen Recipe using chiseled Endstone instead of vanilla End Stone

### ISSUE THREAD

**Issue by VortexJD** [FTBTeam/FTB-Pyramid-Reborn-3.0#7]
* **Modpack Version**: 3.0

* **Issue**: The Resource Generator recipe for End Stone is using the chiseled variant instead of the vanilla block.

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: yes

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by DinnerBeef** [comment]
Thanks you for reporting and issues. I am glad to to you that this had now been fixed and well be available  in the next.

**Comment by DinnerBeef** [comment]
Thanks you for submitting this issue this. The issues has now been fixed and will be available in the next update.
