### ISSUE TITLE
Lava Fabricator Controller recipe

### ISSUE THREAD

**Issue by xenix1337** [FTBTeam/FTB-Pyramid-Reborn-3.0#9]
* **Modpack Version**: 3.0.0

* **Issue**: Recipe of Lava Fabricator Controller isn't changed. It needs 3 buckets of lava, so it's nearly impossible to begin with this.

* **Is it Repeatable?**: I don't know, I just have this problem

* **Mod/s Affected**: Actually Addictions

* **Known Fix**: none

**Comment by DinnerBeef** [comment]
There are other ways for you get to lava in this pack just look in JEI.
